'use client';

import { useState } from 'react';

interface SummaryResultProps {
  videoId: string;
  videoTitle: string;
  summary: string;
  bullets: string[];
  timestamps: { time: string; text: string }[];
  onRegenerate: () => void;
  isLoading: boolean;
}

export default function SummaryResult({
  videoId,
  videoTitle,
  summary,
  bullets,
  timestamps,
  onRegenerate,
  isLoading,
}: SummaryResultProps) {
  const [copiedText, setCopiedText] = useState(false);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);

  const copyToClipboard = async () => {
    const text = `${videoTitle}\n\nSummary:\n${summary}\n\nKey Points:\n${bullets.map((b) => `• ${b}`).join('\n')}${timestamps.length > 0 ? `\n\nTimestamps:\n${timestamps.map((t) => `[${t.time}] ${t.text}`).join('\n')}` : ''}`;

    await navigator.clipboard.writeText(text);
    setCopiedText(true);
    setTimeout(() => setCopiedText(false), 2000);
  };

  const copyAsMarkdown = async () => {
    const md = `# ${videoTitle}\n\n## Summary\n${summary}\n\n## Key Points\n${bullets.map((b) => `- ${b}`).join('\n')}${timestamps.length > 0 ? `\n\n## Timestamps\n${timestamps.map((t) => `- **${t.time}** — ${t.text}`).join('\n')}` : ''}\n\n---\n*Generated by YouTube Summarizer*`;

    await navigator.clipboard.writeText(md);
    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2000);
  };

  return (
    <div className="mx-auto max-w-3xl px-4 py-8">
      {/* Video embed */}
      <div className="mb-8 overflow-hidden rounded-2xl shadow-2xl shadow-gray-200/50 dark:shadow-gray-950/50">
        <div className="aspect-video">
          <iframe
            src={`https://www.youtube.com/embed/${videoId}`}
            title={videoTitle}
            className="h-full w-full"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          />
        </div>
      </div>

      {/* Video Title */}
      <h2 className="mb-6 text-2xl font-bold text-gray-900 dark:text-white">{videoTitle}</h2>

      {/* Action buttons */}
      <div className="mb-6 flex flex-wrap gap-2">
        <button
          onClick={copyToClipboard}
          className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition-all hover:bg-gray-50 hover:shadow-sm dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-750"
        >
          {copiedText ? (
            <>
              <svg className="h-4 w-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
              Copy Text
            </>
          )}
        </button>

        <button
          onClick={copyAsMarkdown}
          className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition-all hover:bg-gray-50 hover:shadow-sm dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-750"
        >
          {copiedMarkdown ? (
            <>
              <svg className="h-4 w-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
              </svg>
              Copy as Markdown
            </>
          )}
        </button>

        <button
          onClick={onRegenerate}
          disabled={isLoading}
          className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-lg shadow-blue-500/20 transition-all hover:shadow-blue-500/30 hover:brightness-110 disabled:opacity-50"
        >
          <svg className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
          Regenerate
        </button>
      </div>

      {/* Summary card */}
      <div className="mb-6 rounded-2xl border border-gray-100 bg-gradient-to-br from-blue-50 via-white to-indigo-50 p-6 shadow-sm dark:border-gray-800 dark:from-blue-950/30 dark:via-gray-900 dark:to-indigo-950/30">
        <div className="mb-3 flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-blue-100 dark:bg-blue-900/50">
            <svg className="h-4 w-4 text-blue-600 dark:text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Summary</h3>
        </div>
        <p className="leading-relaxed text-gray-700 dark:text-gray-300">{summary}</p>
      </div>

      {/* Key Points */}
      <div className="mb-6 rounded-2xl border border-gray-100 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900">
        <div className="mb-4 flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-indigo-100 dark:bg-indigo-900/50">
            <svg className="h-4 w-4 text-indigo-600 dark:text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
            </svg>
          </div>
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Key Points</h3>
        </div>
        <ul className="space-y-3">
          {bullets.map((bullet, i) => (
            <li key={i} className="flex gap-3">
              <span className="mt-1.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-indigo-500 text-xs font-bold text-white">
                {i + 1}
              </span>
              <span className="text-gray-700 dark:text-gray-300">{bullet}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Timestamps */}
      {timestamps.length > 0 && (
        <div className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900">
          <div className="mb-4 flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-purple-100 dark:bg-purple-900/50">
              <svg className="h-4 w-4 text-purple-600 dark:text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Timestamps</h3>
          </div>
          <div className="space-y-2">
            {timestamps.map((ts, i) => (
              <div key={i} className="flex gap-3 rounded-lg p-2 transition-colors hover:bg-gray-50 dark:hover:bg-gray-800">
                <span className="shrink-0 rounded-md bg-purple-100 px-2.5 py-0.5 font-mono text-sm font-semibold text-purple-700 dark:bg-purple-900/50 dark:text-purple-300">
                  {ts.time}
                </span>
                <span className="text-gray-700 dark:text-gray-300">{ts.text}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
